# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build:
      context: .
      args:
        DASHBOARDS_VER: '0.6.*'
        DECLWIDGETS_VER: '0.7.*'
        CMS_VER: '0.5.*'
        BUNDLER_VER: '0.8.*'
    image: zos-spark/i2w-notebook
    container_name: ${NAME}
    volumes:
     - "work:/home/jovyan/work"
    ports:
     - "${PORT}:8888"

volumes:
  work:
    external:
      name: ${WORK_VOLUME}
